### ISSUE TITLE
Bug and Suggestion

### ISSUE THREAD

**Issue by DevTimur** [Shadows-of-Fire/Attained-Drops-2#10]
Vitalized soil does not have localisation
https://i.imgur.com/wBbQza2.png

Suggestions:
1) Is it possible to make custom plants using Crafttweaker? If not, can you add this? It would be nice to have alternative to Magical crops. Especially if it looks better.
2) Can you make so Bulb grow in multiple stages? Like Cocoa beens.
3) Can you add Right-click harvestability? It would allow automation using Industial Foregoing or Mechanical user. (If that doesn't interfere with your intention to make it Manual harvest only)

**Comment by Shadows-of-Fire** [comment]
Weird.  I swear it was localized and I haven't changed anything relating to that.  Eh, simple fix.  
As for the other things:
1. No.  Maybe, but it would require a tile entity at the least, which isn't always the best case for plants.  Or a total rewrite to incorporate that kind of system without exploding into a ton of block ids...
2. Unlikely - that would triple the number of models required for each bulb, and then the bulb would also have to receive growth ticks, which it currently does not do.
3. Makes sense for a config option, so probably.
