### ISSUE TITLE
Suggestion: Compatibility with Immersive Engineering Garden Cloches

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/Attained-Drops-2#13]
On version 0.10-58 of Immersive Engineering the Garden Cloche was added with support for Attained Drops, but on version 3.7.3 of Attained Drops 2 the Garden Cloche doesn't recognize Vitalized Seeds.

**Comment by Shadows-of-Fire** [comment]
That support was added on IE's end, and was never updated.  I don't even know if I can do anything from my end.  I made a note about the rewrite that this mod underwent, but he never updated it.

**Comment by Shadows-of-Fire** [comment]
Making a PR to resolve this seeing as it's been unfixed since 1.11

**Comment by ghost** [comment]
Wow! Thank you for working so quickly on this!
