### ISSUE TITLE
[1.13.2] Sever Crash on load

### ISSUE THREAD

**Issue by Morpheus1101** [Shadows-of-Fire/Attained-Drops-2#14]
Forge: 25.0.22
AD vers:  4.0.0

[crash-2019-02-18_07.00.51-server.txt](https://github.com/Shadows-of-Fire/Attained-Drops-2/files/2873414/crash-2019-02-18_07.00.51-server.txt)

**Comment by Shadows-of-Fire** [comment]
Fixed in 4.0.1
