### ISSUE TITLE
[1.14.4] Please update to forge .45 due to the breaking changes in forge.

### ISSUE THREAD

**Issue by ProsperCraft** [Shadows-of-Fire/Attained-Drops-2#15]
AttainedDrops-1.14.4-5.1.1 crashes the client and server on load.

[latest.log](https://github.com/Shadows-of-Fire/Attained-Drops-2/files/3488441/latest.log)
[debug.log](https://github.com/Shadows-of-Fire/Attained-Drops-2/files/3488442/debug.log)

**Comment by Shadows-of-Fire** [comment]
no part of this log is caused by ad2

**Comment by ProsperCraft** [comment]
Yes, sorry, my test environment got buggered up by a bad BoP update.
