### ISSUE TITLE
[Feature] Add guardian drops: prismarine shard and/or crystal

### ISSUE THREAD

**Issue by codetaylor** [Shadows-of-Fire/Attained-Drops-2#2]
Thanks for this great mod! :)

Is prismarine something that you would be open to adding to the mod, or was it left out by design? I am happy to submit a pull request for it, but I wanted to check and see if it's something that you're interested in before doing the work or stepping on toes.

**Comment by Shadows-of-Fire** [comment]
Prismarine was left out because it wasn't part of the original mod, this was basically an almost direct port from 1.7, with some code cleanup and minor tweaks.

**Comment by Shadows-of-Fire** [comment]
Its more of I don't have a texture for it, so it doesn't exist.  
And believe me, I cannot make textures.
