### ISSUE TITLE
[1.15.2] Unable to craft Vitalized Seed

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/Attained-Drops-2#22]
I added AD2 to my modpack, and while the recipe for the Vitalized Seed shows up in JEI, the Seed itself is uncraftable. Placing the items in the crafting table does not output the seed. I was able to work around this by removing and then re-adding the recipe using CraftTweaker.

Minecraft 1.15.2
Forge 31.2.41
Attained Drops 2 6.0.7
Placebo 3.1.0

**Comment by chunkedelement** [comment]
Thanks for this solution I had the same issue and the crafttweker remove and add.shapeless recipe worked great.

Minecraft 1.15.2
Forge 31.2.47
Attained Drops 2 6.0.7
