### ISSUE TITLE
When I plant a wither skull and grow it, harvesting it gives a white skeleton skull instead of a wither one.

### ISSUE THREAD

**Issue by Lothrazar** [Shadows-of-Fire/Attained-Drops-2#6]
The top part of the plant and the soil are both black however. I would expect a wither skeleton skull to drop since thats what I put in the soil.

I was playing in 1.11.2  ( AttainedDrops-1.11.2-2.3.0.jar )

![skull](https://cloud.githubusercontent.com/assets/621529/24343807/3aec2f18-127d-11e7-89c2-91468d388e58.png)

**Comment by Shadows-of-Fire** [comment]
Hm. Pass wrote this part, I'll see what's up.

**Comment by Shadows-of-Fire** [comment]
Nothing looks like its wrong anywhere... @p455w0rd any idea what might be up?
