### ISSUE TITLE
1.12.2 server crash with ad 3.5.2

### ISSUE THREAD

**Issue by digi-tal-it** [Shadows-of-Fire/Attained-Drops-2#7]
I updated attained drops from 3.5.1 to 3.5.2 and I am getting this crash on my 1.12.2 server:

https://pastebin.com/cHTDZ1g1

mc 1.12.2
forge 14.23.0.2501
attained drops 3.5.2

**Comment by jc2xs** [comment]
I'll 2nd this report.  I'm having the same issue on a server I'm setting up
https://pastebin.com/PSewA5uf

MInecraft 1.12.2
forge 14.23.0.2503
Attained Drops 3.5.2

**Comment by Shadows-of-Fire** [comment]
I guess I never got the email for this one.  Fixed in 3.5.3
